### PR TITLE
Fifo lifo

### PR DESCRIPTION
**Pull request by sbarral**
This PR moves the former LIFO queue into a `lifo` module and adds a FIFO queue with the same API in a `fifo` module. The FIFO queue uses the same algorithm as `tokio`'s local queue.

Questions to be resolved before merging:
* should a common trait be defined to abstract over the 2 queues?
* alternatively, should there just be 1 queue with 2 flavours like in `crossbeam::dequeue`? I am not too fond of this approach because I can't really imagine a situation where the FIFO or LIFO behavior would be selected at run-time, and run-time selection does incur a small cost (probably very small, admittedly), but I am ready to hear arguments for it.

TODO: update the README.

### CODE REVIEW

**Comment by nullchinchilla** [comment]
I think it's okay to either just leave them separate, or have 1 queue with 2 flavors. A trait would not really help easily changing a codebase to use one or the other etc.

> I can't really imagine a situation where the FIFO or LIFO behavior would be selected at run-time

I can: a `SMOLSCALE_UNFAIR` environment variable that configures `smolscale` to prioritize throughput over fairness, by using things like LIFO, stealing/balancing less frequently, etc :)

**Comment by sbarral** [comment]
> > I can't really imagine a situation where the FIFO or LIFO behavior would be selected at run-time
> 
> I can: a `SMOLSCALE_UNFAIR` environment variable that configures `smolscale` to prioritize throughput over fairness, by using things like LIFO, stealing/balancing less frequently, etc :)

You are right, this would be a legitimate use-case, which made me look into `crossbeam_deque` to see how it was designed. Unfortunately this made me aware that the "flavor" approach would be much more difficult to pull off for `st3`. In `crossbeam_deque` there is indeed a very large amount of code re-use and I can see why they went that way. In fact, the atomics are the same for the 2 `crossbeam_deque` flavors and most of the code does not even need to be aware of the flavor.

In the case of `st3`, the LIFO algorithm is very different from its FIFO counterpart: all atomics are different and the LIFO queue even uses 1 extra atomic compared to the FIFO.
Factoring in the fact that a "flavored" queue would also need to allow stealing between queues of different flavors, I increasingly feel that I would be trying to fit a square peg in a round hole.

So even though you do make a good point in favor run-time selection, I am afraid that this is just too much trouble.

> A trait would not really help easily changing a codebase to use one or the other etc.

Yes, that would be more painful than with flavors, but it is still a step up compared to using macros to abstract over the 2 queues (which is what I currently in many tests). A use case would be for instance a library that would provide an algorithm or extension on `st3`. But then this use-case is perhaps uncommon enough that it can be ignored. My hesitation comes from the fact  that adding a trait later would be another breaking change. But then, I guess such breaking change would not be anything terrible for a pre-1.0 library, so I am probably overthinking it ;-)

**Comment by nullchinchilla** [comment]
The naive way of doing the two flavors would obviously just to have an enum that has both cases, and forwards each method to the wrapped value. That would be a simple wrapper around the existing code, and shouldn't complicate things too much.

 I don't imagine this to add measurable overhead --- CPU caches / branch prediction is *extremely* good at optimizing this sort of thing.

**Comment by sbarral** [comment]
Yeah, maybe I am trying to find myself excuses not to do the extra work ;-)

I am a bit busy right now but I will try to get a flavor-based prototype by the end of the week.

**Comment by sbarral** [comment]
> One slightly unrelated thing: I remember Tokio uses some sort of intrusive linked list as its global task queue --- is that crucial for performance, or is just a regular `ConcurrentQueue`/`SeqQueue` good enough? (BTW, do you know anything about `concurrent-queue` vs `crossbeam-queue`?).

This is a good question. If tasks were popped one-by-one, then I would definitely expect `SeqQueue` to be faster. But in `tokio` and `asynchronix` the tasks are popped in batches, in which case I expect a mutex-based queue to be faster in practice because `SegQueue` needs atomic operations for each `pop`, whereas moving a batch only needs to lock the mutex once for many tasks.

In fact, in `asynchronix` I took this logic to the extreme and just have a simple mutex-protected `Vec<Batch>` (you could use a instead a `VecDeque` if you need fairness) were a `Batch` is basically just a `Vec<Task>` that can hold up to half the capacity of a local queue.
The advantage is that moving a batch of tasks is very fast since (i) the mutex is only held for very short (just the time to move out the batch, which just needs to copy the pointer and a couple of other bytes) and (ii) the tasks are stored contiguously in memory so copying a batch of tasks to the local queue is much faster than with a linked list. But I'll be honest, I have not measured the performance so this is entirely based on somewhat theoretical expectations.

AFAIK the bounded versions of `ConcurrentQueue` is pretty much the same as `crossbeam::ArrayQueue` so it's reasonable to think that the unbounded versions are also similar (I am pretty sure both were written by Stjepan), but I don't really know if this is the case nor why this split exists.

**Comment by nullchinchilla** [comment]
Yeah, that makes sense. I might just switch to a `VecDeque<Runnable>`, though I'm a bit concerned because tasks would be *pushed* onto it one by one

**Comment by sbarral** [comment]
I have experimented with an ugly naive enum-based queue that wraps both the LIFO and FIFO in the `bivariant-queue` branch, and indeed there is no meaningful difference in benchmarks.

But ultimately, I couldn't get myself to force users to accept the resulting code bloat for what should be a low-level, highly optimized primitive. Each method is now twice bigger in terms of instruction count, so there is a very real possibility that it could impact compiler inlining decisions in user code.

OTOH, an enum-based wrapper queue can be implemented fully on the user side without loss of performance (it's about 100LOC), so if someone needs it badly there is the DIY option. The only thing that cannot be implemented on the user side is stealing from a LIFO to a FIFO or from a FIFO to a LIFO, but I don't expect that to be useful in practice.

So after staying on the fence for more than a week, I decided to merge the PR with 2 distinct queues, having in mind that a variant-agnostic queue can always be added on top of that later. I will not publish a new version immediately, however, because I consider including other API-breaking changes with the next release to avoid having to break API again later on. 

> I might just switch to a `VecDeque`, though I'm a bit concerned because tasks would be _pushed_ onto it one by one

Sorry, you are right, my reply was biased towards my personal use-case where pushing tasks is a negligible part of the overall computational cost and is only done by one thread (in my case the global queue is mainly accessed when storing/loading the overflow from local queues).

**Comment by sbarral** [comment]
[Released in v0.4.0]

**Pull request merged**
